# name: Node.js CI

# on:
#   push:
#     branches: [ "master" ]
# jobs:
#   build:
#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [ 18.x ]

#     steps:
#     - uses: actions/checkout@v4
#     - run : cd Backend && pwd 
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm ci
    
#     - name: Build application
#       run: npm run build
name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v4
    
    # Step to move files from 'backend' folder to root folder
    - name: Move files to root folder
      run: |
        mv Backend/* .
        mv Backend/.* . || true  
        
    # Confirm the current directory after move
    - name: Confirm directory after move
      run:  ls -la

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build

